### ISSUE TITLE
Replace BR element in any heading element with `_`

### ISSUE THREAD

**Issue by anasram** [ndabas/toc#9] opened 2017-02-26 19:08 UTC
`<br/>` element within any heading element —if any— should be replaced with `_`.
e.g.: `<h2>Heading<br/>Sub Heading</h2>` returns  `#HeadingSub_Heading`, while it should be `#Heading_Sub_Heading`

**Comment by ndabas** [comment] 2019-09-08 20:42
While I agree with what the expected behavior should be, there is no straightforward fix for the issue. This is because of the way jQuery handles `.text()` -- `<br>` tags are not converted to line breaks.

The simple workaround is to write headings with line breaks with an additional line break in the HTML, like this:

```
<h2>Live<br>
Example</h2>
```

Just a simple space will do as well: `<h2>Live<br> Example</h2>`. Neither of these will affect the browser rendering of the text, and both will get the library to generate the expected IDs.

Closing this as wontfix.

**Closed by ndabas** 2019-09-08 20:42 UTC
Labels: wontfix
